### PR TITLE
Increase timeout for postcodeinfo calls

### PR DESCRIPTION
**Pull request by niallcreech**
When we search for a partial postcode, and the postcodeinfo service has not
already cached the result, the time taken to fetch the result is greater than
the default 5 second timeout for the postcodeinfo client. This changes increases
the timeout to 30 seconds, which is greater than the observed maximum partial
search query time of ~25 seconds. The timeout can also be specified using the
POSTCODEINFO_API_TIMEOUT environment variable.

### CODE REVIEW

**Comment by niallcreech** [comment]
Tested well on dev https://courtfinder-dev.dsd.io/search/results?aol=all&postcode=Nw6

**Comment by dotemacs** [comment]
Wow, that is one ugly looking URL.

**Comment by niallcreech** [comment]
@dotemacs I assume its mother loves it nonetheless :)

**Comment by pwyborn** [comment]
Looks ok to me

**Pull request merged**
